// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using examencsharp;

#nullable disable

namespace examencsharp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260309082104_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("examencsharp.Models.Candidat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<int>("FokontanyId")
                        .HasColumnType("int");

                    b.Property<string>("NomCandidat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PrenomCandidat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Programme")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Validated")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("FokontanyId");

                    b.ToTable("Candidats");
                });

            modelBuilder.Entity("examencsharp.Models.CinRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CitoyenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CitoyenId");

                    b.ToTable("CinRequests");
                });

            modelBuilder.Entity("examencsharp.Models.Citoyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CIN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FokontanyId")
                        .HasColumnType("int");

                    b.Property<string>("NomCitoyen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PrenomCitoyen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FokontanyId");

                    b.HasIndex("UtilisateurId")
                        .IsUnique();

                    b.ToTable("Citoyens");
                });

            modelBuilder.Entity("examencsharp.Models.Election", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateElection")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FokontanyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TitreElection")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FokontanyId");

                    b.ToTable("Elections");
                });

            modelBuilder.Entity("examencsharp.Models.Fokontany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Commune")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomFokontany")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Fokontany");
                });

            modelBuilder.Entity("examencsharp.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code2FA")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Expiration2FA")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("examencsharp.Models.Views.VCandidate", b =>
                {
                    b.Property<string>("Election")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Fokontany")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Validated")
                        .HasColumnType("tinyint(1)");

                    b.ToTable((string)null);

                    b.ToView("V_candidates", (string)null);
                });

            modelBuilder.Entity("examencsharp.Models.Views.VDashboard", b =>
                {
                    b.Property<int>("CinDelivered")
                        .HasColumnType("int");

                    b.Property<int>("PendingRequests")
                        .HasColumnType("int");

                    b.Property<int>("TotalCitizens")
                        .HasColumnType("int");

                    b.Property<int>("TotalVotes")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("V_dashboard", (string)null);
                });

            modelBuilder.Entity("examencsharp.Models.Views.VParticipationRate", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<double>("ParticipationRate")
                        .HasColumnType("double");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable((string)null);

                    b.ToView("V_participation_rate", (string)null);
                });

            modelBuilder.Entity("examencsharp.Models.Views.VResult", b =>
                {
                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TotalVotes")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("V_results", (string)null);
                });

            modelBuilder.Entity("examencsharp.Models.Views.VTotalVoters", b =>
                {
                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<int>("TotalVoters")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("V_total_voters", (string)null);
                });

            modelBuilder.Entity("examencsharp.Models.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidatId")
                        .HasColumnType("int");

                    b.Property<int>("CitoyenId")
                        .HasColumnType("int");

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("VoteDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CandidatId");

                    b.HasIndex("CitoyenId");

                    b.HasIndex("ElectionId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("examencsharp.Models.VoteLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CitoyenId")
                        .HasColumnType("int");

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CitoyenId");

                    b.HasIndex("ElectionId");

                    b.ToTable("VoteLogs");
                });

            modelBuilder.Entity("examencsharp.Models.Candidat", b =>
                {
                    b.HasOne("examencsharp.Models.Election", "Election")
                        .WithMany("Candidats")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("examencsharp.Models.Fokontany", "Fokontany")
                        .WithMany("Candidats")
                        .HasForeignKey("FokontanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Election");

                    b.Navigation("Fokontany");
                });

            modelBuilder.Entity("examencsharp.Models.CinRequest", b =>
                {
                    b.HasOne("examencsharp.Models.Citoyen", "Citoyen")
                        .WithMany("CinRequests")
                        .HasForeignKey("CitoyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Citoyen");
                });

            modelBuilder.Entity("examencsharp.Models.Citoyen", b =>
                {
                    b.HasOne("examencsharp.Models.Fokontany", "Fokontany")
                        .WithMany("Citoyens")
                        .HasForeignKey("FokontanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("examencsharp.Models.Utilisateur", "Utilisateur")
                        .WithOne("Citoyen")
                        .HasForeignKey("examencsharp.Models.Citoyen", "UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fokontany");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("examencsharp.Models.Election", b =>
                {
                    b.HasOne("examencsharp.Models.Fokontany", "Fokontany")
                        .WithMany("Elections")
                        .HasForeignKey("FokontanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fokontany");
                });

            modelBuilder.Entity("examencsharp.Models.Vote", b =>
                {
                    b.HasOne("examencsharp.Models.Candidat", "Candidat")
                        .WithMany("Votes")
                        .HasForeignKey("CandidatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("examencsharp.Models.Citoyen", "Citoyen")
                        .WithMany("Votes")
                        .HasForeignKey("CitoyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("examencsharp.Models.Election", "Election")
                        .WithMany("Votes")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidat");

                    b.Navigation("Citoyen");

                    b.Navigation("Election");
                });

            modelBuilder.Entity("examencsharp.Models.VoteLog", b =>
                {
                    b.HasOne("examencsharp.Models.Citoyen", "Citoyen")
                        .WithMany()
                        .HasForeignKey("CitoyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("examencsharp.Models.Election", "Election")
                        .WithMany()
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Citoyen");

                    b.Navigation("Election");
                });

            modelBuilder.Entity("examencsharp.Models.Candidat", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("examencsharp.Models.Citoyen", b =>
                {
                    b.Navigation("CinRequests");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("examencsharp.Models.Election", b =>
                {
                    b.Navigation("Candidats");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("examencsharp.Models.Fokontany", b =>
                {
                    b.Navigation("Candidats");

                    b.Navigation("Citoyens");

                    b.Navigation("Elections");
                });

            modelBuilder.Entity("examencsharp.Models.Utilisateur", b =>
                {
                    b.Navigation("Citoyen");
                });
#pragma warning restore 612, 618
        }
    }
}
